### ISSUE TITLE
Endpoints For New Game

### ISSUE THREAD

**Issue by MangoSwirl** [HighlanderRobotics/Scouting-Server#17]
(Done) Discuss new endpoints for Power Play here.

# Endpoints necessary for final Figma design

## Category metrics
There should be one endpoint that returns the `value` of all of these. There should also be an additional endpoint for each top-level metric that returns its details.
- [x] Cone delivery cycle time
   - [x] Value
   - [x] Array over time
   - [x] All teams
   - [x] Difference
- [x] Cube delivery cycle time
   - [x] Value
   - [x] Array over time
   - [x] All teams
   - [x] Difference
- [x] Average # of cones placed in auto
   - [x] Value
   - [x] Array over time
   - [x] All teams
   - [x] Difference
- [x] Average # of cubes placed in auto
   - [x] Value
   - [x] Array over time
   - [x] All teams
   - [x] Difference
- [x] Average # of cones placed in teleop
   - [x] Value
   - [x] Array over time
   - [x] All teams
   - [x] Difference
- [x] Average # of cubes placed in teleop
   - [x] Value
   - [x] Array over time
   - [x] All teams
   - [x] Difference
- [x] Average cycle time for cones in teleop
   - [x] Value
   - [x] Array over time
   - [x] All teams
   - [x] Difference
- [x] Average cycle time for cubes in teleop
   - [x] Value
   - [x] Array over time
   - [x] All teams
   - [x] Difference
- [x] Maximum row for cones
- [x] Maximum row for cubes
- [ ] Average pins
   - [x] Value
   - [x] Array over time
   - [x] All teams
   - [x] Difference
- [x] Average blocks
   - [x] Value
   - [x] Array over time
   - [x] All teams
   - [x] Difference
- [ ] Impact on opposing alliance score
   - [ ] Value
   - [ ] Array over time
   - [ ] All teams
   - [ ] Difference

## Breakdown metrics
Another endpoint to get all of these.
- [x] Role
   - [x] # of matches a placer
   - [x] # of matches on defense
   - [x] # of matches on delivery
- [x] Charge station teleop
   - [x] Times docked
   - [x] Times engaged
   - [x] Times failed
   - [x] Times didn't attempt (Maybe)
- [x] Charge station auto
   - [x] Times docked
   - [x] Times engaged
   - [x] Times failed
   - [x] Times didn't attempt (Maybe)

**Comment by CassieColby** [comment]
- [ ] climber (precent for all 3 levels) + array
- [ ] climber overall
- [ ] climber difference
- [ ] cones per game avg + array
- [ ] cones overall
- [ ] cones difference 
- [ ] cubes for game avg + array
- [ ] cubes overall
- [ ] cubes difference
- [ ] cones avg auto + array
- [ ] cones overall auto
- [ ] cones difference auto
- [ ]  climber auto + array
- [ ] climber all overall auto
- [ ] climber difference auto
- [ ] notes



All of these are done, however they 1 have not been tested (no sample data) and 2 have not fully been catered to how exactly the numbers are gonna be (ex: what number will correlate to dropping an item at the station)

**Comment by CassieColby** [comment]
- [ ] cube cycle time
- [ ] cube cycle time over all
- [ ] cube cycle time difference 
- [ ] cone cycle time
- [ ] cone cycle time over all
- [ ] cone cycle time difference 
- [ ] robot roles (giving % for each role : offense, defense, mixed, helper)

**Comment by CassieColby** [comment]
FOR OVERVIEW ONLY 

- [ ] charge station precent engaged
- [ ] precent fail
- [ ] cones avg count
- [ ] avg cycle time
- [ ] max row
- [ ] cubes avg count
- [ ] cubes avg cycle tme
- [ ] max row
- [ ] avg pins
- [ ] avg blocks
- [ ] opponents impacs

**Comment by MangoSwirl** [comment]
Updated original comment with endpoints.

**Comment by MangoSwirl** [comment]
Originally `overview` returned category metrics and notes. Since they are now separate tabs, the `overview` endpoint will be split into `categoryMetrics`, `notes`, and there will be the addition of `breakdowns`.

**Comment by MangoSwirl** [comment]
> FOR OVERVIEW ONLY
> 
> * [x]  charge station precent engaged
> * [x]  precent fail
> * [x]  cones avg count
> * [x]  cone avg cycle time to team
> * [x]  cone avg cycle time to score
> * [x]  cubes avg count
> * [x]  cubes avg cycle time to team
> * [x]  cubes avg cycle time to score
> * [x]  max row cubes
> * [x]  max row cones
> * [x]  avg pins
> * [x]  avg blocks
> * [ ]  opponents impacs

"opponents impacs" is the impact on the opposing alliances' scores, not collisions with other robots, right?
